[phases.setup]
nixPkgs = ["nodejs_18", "postgresql_15"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build:server", "npm run build:client"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production" 