[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "smart-task-automation-engine"

[build.environment]
NODE_ENV = "production"

[build.phases]
install = ["npm ci"]
build = ["npm run build:server", "npm run build:client"] 